version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # ajuste se seu app rodar em outra porta
    environment:
      - PYTHONUNBUFFERED=1
